# Generated by Django 2.2.1 on 2019-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190530_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='singleProductPrice',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.CharField(max_length=100000),
        ),
    ]
