# Generated by Django 2.2.1 on 2019-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190531_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.CharField(max_length=300),
        ),
    ]
