# Generated by Django 2.2.1 on 2019-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190601_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='singleProductPrice',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(max_length=100),
        ),
    ]
