# Generated by Django 2.2.1 on 2019-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190601_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productName',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(),
        ),
    ]
