# Generated by Django 2.2.1 on 2019-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190601_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='singleProductPrice',
            field=models.IntegerField(),
        ),
    ]
