# Generated by Django 2.2.1 on 2019-06-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190603_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productName',
            new_name='productList',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productQuantite',
            new_name='productTotalPrice',
        ),
    ]
