# Generated by Django 2.2.1 on 2019-06-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190603_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productList',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productTotalPrice',
            new_name='productQuantite',
        ),
    ]
